version: '3'
services:
  springboot-app:
    image: vishujava6541/spring-boot-h2-mysql:latest
    container_name: springboot-app
    ports:
      - "8080:8080"
    volumes:
     - /home/vishu/Documents/docker_volume/logs:/tmp
    environment:
     - SPRING_PROFILE=production
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
     - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD= 
      - MYSQL_DATABASE= march_learning
 
volumes:
  db_volume: 
    driver: local
    driver_opts:
      type: none
      device: /home/vishu/Documents/docker_volume/database
      o: bind

