version: '3'
services:
  springboot-app:
    image: h2db:1
    container_name: springboot-app
    ports:
      - "8080:8080"
    volumes:
     - /home/vishu/Documents/docker_volume/logs:/tmp
    environment:
     - SPRING_PROFILE=production
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD= 
      - MYSQL_DATABASE=
